all: reference_implementation student_submission

reference_implementation:
	g++ -Wall -o reference_implementation -O3 reference_implementation.cpp

student_submission:
	g++ -Wall -o student_submission -O3 student_submission.cpp
